// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import("ant-design-vue/es")["Alert"]
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APageHeader: typeof import("ant-design-vue/es")["PageHeader"]
    BaseModal: typeof import("./src/components/base/BaseModal.vue")["default"]
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    NewsForm: typeof import('./src/components/NewsForm.vue')['default']
    NewsList: typeof import('./src/components/NewsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheNavbar: typeof import("./src/components/TheNavbar.vue")["default"]
    UserModal: typeof import('./src/components/UserModal.vue')['default']
  }
}
